FROM node:24-slim

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN --mount=type=secret,id=app_env,target=/app/.env \
    npm run build && rm -rf .next/cache

ENV NODE_ENV=production

EXPOSE 3000

CMD ["npm", "run", "start"]
