services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
      secrets:
        - app_env
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - able-alliance-net
    depends_on:
      mongo:
        condition: service_healthy
      cas:
        condition: service_started
    command: npm run start

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    networks:
      - able-alliance-net
    volumes:
      - mongodb-data:/data/db
    logging:
      driver: "none"
    healthcheck:
      test:
        ["CMD", "mongosh", "--eval", "db.adminCommand({ ping: 1 })", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  cas:
    build:
      context: ./mock-cas-server
      dockerfile: Dockerfile
    env_file: .env
    environment:
      PORT: "8443"
    ports:
      - "8443:8443"
    networks:
      - able-alliance-net

  websocket:
    build:
      context: .
      dockerfile: websocket-server/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      mongo:
        condition: service_healthy
    env_file: .env
    environment:
      PORT: "4000"
    networks:
      - able-alliance-net

networks:
  able-alliance-net:
    driver: bridge

volumes:
  mongodb-data:

secrets:
  app_env:
    file: .env
